name: Deploy On Main

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup, Build, and Start App
        uses: ./.github/actions/setup
      - name: Use Cypress Test Action
        uses: ./.github/actions/cypress-test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cypress-project-id: ${{ secrets.NEXT_PUBLIC_CYPRESS_ID }}
          cypress-record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
  deploy:
    runs-on: ubuntu-latest
    needs: cypress-run
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Vercel Deploy Action
        uses: ./.github/actions/vercel-deployment
        with:
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
